include "application"
include "local-shared"

shopping-cart-service.grpc.port = 8102
shopping-cart-service.http.port = 8081


akka.management.http.port = 9102
akka.remote.artery.canonical.port = 2552
